import { Manrope, Playfair_Display, WindSong } from 'next/font/google'
import Script from 'next/script'

import { ThemeProvider } from '@/components/ThemeProvider'
import NavContent from '@/components/navigation/NavContent'
import localFont from 'next/font/local'

import StyledJsxProvider from '@/components/StyledJsxProvider'
import Navbar from '@/components/navigation/Navbar'
import { cn } from '@/lib/utils'
import '@radix-ui/themes/styles.css'
import { Toaster } from 'sonner'
import './globals.css'
import './theme-config.css'

// core styles shared by all of react-notion-x (required)
// import 'react-notion-x/src/styles.css'

// used for code syntax highlighting (optional)
// import 'prismjs/themes/prism-tomorrow.css'

const juventusFont = localFont({
  src: '../../assets/JuventusFans--bold.woff2',
  display: 'swap',
  variable: '--font-juventus-bold'
})

const manrope = Manrope({
  subsets: ['latin', 'latin-ext'],
  variable: '--font-manrope'
})

const windsong = WindSong({ subsets: ['latin'], weight: ['500'] })

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children, params }) {
  return (
    <html suppressHydrationWarning lang="en">
      <Script
        async
        src="https://analytics.eu.umami.is/script.js"
        data-website-id="51da5491-5516-4d13-a72a-f2ede7a1f612"
      />

      <Script
        src="https://cdn.apple-mapkit.com/mk/5.x.x/mapkit.core.js"
        async
        data-callback="initMapKit"
        data-libraries="map"
      />

      <body
        className={`${manrope.variable} ${juventusFont.variable} ${playfairDisplay.variable}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <StyledJsxProvider>
            <Toaster />
            <main className="relative flex h-full min-h-screen w-full md:py-2">
              <div
                className="absolute inset-0 z-10 h-full w-full opacity-50"
                style={{
                  backgroundImage:
                    'url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAMAAAAp4XiDAAAAUVBMVEWFhYWDg4N3d3dtbW17e3t1dXWBgYGHh4d5eXlzc3OLi4ubm5uVlZWPj4+NjY19fX2JiYl/f39ra2uRkZGZmZlpaWmXl5dvb29xcXGTk5NnZ2c8TV1mAAAAG3RSTlNAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAvEOwtAAAFVklEQVR4XpWWB67c2BUFb3g557T/hRo9/WUMZHlgr4Bg8Z4qQgQJlHI4A8SzFVrapvmTF9O7dmYRFZ60YiBhJRCgh1FYhiLAmdvX0CzTOpNE77ME0Zty/nWWzchDtiqrmQDeuv3powQ5ta2eN0FY0InkqDD73lT9c9lEzwUNqgFHs9VQce3TVClFCQrSTfOiYkVJQBmpbq2L6iZavPnAPcoU0dSw0SUTqz/GtrGuXfbyyBniKykOWQWGqwwMA7QiYAxi+IlPdqo+hYHnUt5ZPfnsHJyNiDtnpJyayNBkF6cWoYGAMY92U2hXHF/C1M8uP/ZtYdiuj26UdAdQQSXQErwSOMzt/XWRWAz5GuSBIkwG1H3FabJ2OsUOUhGC6tK4EMtJO0ttC6IBD3kM0ve0tJwMdSfjZo+EEISaeTr9P3wYrGjXqyC1krcKdhMpxEnt5JetoulscpyzhXN5FRpuPHvbeQaKxFAEB6EN+cYN6xD7RYGpXpNndMmZgM5Dcs3YSNFDHUo2LGfZuukSWyUYirJAdYbF3MfqEKmjM+I2EfhA94iG3L7uKrR+GdWD73ydlIB+6hgref1QTlmgmbM3/LeX5GI1Ux1RWpgxpLuZ2+I+IjzZ8wqE4nilvQdkUdfhzI5QDWy+kw5Wgg2pGpeEVeCCA7b85BO3F9DzxB3cdqvBzWcmzbyMiqhzuYqtHRVG2y4x+KOlnyqla8AoWWpuBoYRxzXrfKuILl6SfiWCbjxoZJUaCBj1CjH7GIaDbc9kqBY3W/Rgjda1iqQcOJu2WW+76pZC9QG7M00dffe9hNnseupFL53r8F7YHSwJWUKP2q+k7RdsxyOB11n0xtOvnW4irMMFNV4H0uqwS5ExsmP9AxbDTc9JwgneAT5vTiUSm1E7BSflSt3bfa1tv8Di3R8n3Af7MNWzs49hmauE2wP+ttrq+AsWpFG2awvsuOqbipWHgtuvuaAE+A1Z/7gC9hesnr+7wqCwG8c5yAg3AL1fm8T9AZtp/bbJGwl1pNrE7RuOX7PeMRUERVaPpEs+yqeoSmuOlokqw49pgomjLeh7icHNlG19yjs6XXOMedYm5xH2YxpV2tc0Ro2jJfxC50ApuxGob7lMsxfTbeUv07TyYxpeLucEH1gNd4IKH2LAg5TdVhlCafZvpskfncCfx8pOhJzd76bJWeYFnFciwcYfubRc12Ip/ppIhA1/mSZ/RxjFDrJC5xifFjJpY2Xl5zXdguFqYyTR1zSp1Y9p+tktDYYSNflcxI0iyO4TPBdlRcpeqjK/piF5bklq77VSEaA+z8qmJTFzIWiitbnzR794USKBUaT0NTEsVjZqLaFVqJoPN9ODG70IPbfBHKK+/q/AWR0tJzYHRULOa4MP+W/HfGadZUbfw177G7j/OGbIs8TahLyynl4X4RinF793Oz+BU0saXtUHrVBFT/DnA3ctNPoGbs4hRIjTok8i+algT1lTHi4SxFvONKNrgQFAq2/gFnWMXgwffgYMJpiKYkmW3tTg3ZQ9Jq+f8XN+A5eeUKHWvJWJ2sgJ1Sop+wwhqFVijqWaJhwtD8MNlSBeWNNWTa5Z5kPZw5+LbVT99wqTdx29lMUH4OIG/D86ruKEauBjvH5xy6um/Sfj7ei6UUVk4AIl3MyD4MSSTOFgSwsH/QJWaQ5as7ZcmgBZkzjjU1UrQ74ci1gWBCSGHtuV1H2mhSnO3Wp/3fEV5a+4wz//6qy8JxjZsmxxy5+4w9CDNJY09T072iKG0EnOS0arEYgXqYnXcYHwjTtUNAcMelOd4xpkoqiTYICWFq0JSiPfPDQdnt+4/wuqcXY47QILbgAAAABJRU5ErkJggg==)'
                }}
              ></div>
              <div className="absolute inset-0 z-20 h-full w-full bg-background opacity-95"></div>
              <div
                style={{ backgroundSize: '400% 400%' }}
                className="absolute inset-0 z-0 h-full w-full animate-gradient bg-gradient-to-br from-blue-500 via-orange-400 to-purple-500"
              ></div>

              <div className="relative z-30 h-screen w-0 shrink-0 overflow-hidden transition-all md:h-[calc(100vh-16px)] md:w-64 md:px-4">
                <NavContent showCmdBtn={true} />
              </div>
              <div className="relative z-30 h-screen w-full overflow-hidden overflow-y-scroll bg-background md:h-[calc(100vh-16px)] md:rounded-l-lg md:border-y md:border-l">
                {/* <div
                  className="pointer-events-none absolute top-1 z-30 h-14 w-[calc(100%-8px)] select-none opacity-95 backdrop-blur-[5px] after:absolute
                after:left-0 after:top-0 after:bg-gradient-to-b after:from-background
                after:to-transparent after:content-[''] first:top-0
                first:-mb-14 md:sticky md:h-20 md:rounded-tl-lg first:md:-mb-20
                "
                  style={{
                    WebkitMaskImage:
                      'linear-gradient(to bottom, rgba(0,0,0,1) 25%, transparent)',
                    maskImage:
                      'linear-gradient(to bottom, rgba(0,0,0,1) 25%, transparent)'
                  }}

                ></div> */}
                <div className="relative flex min-h-screen flex-col px-4 md:min-h-[calc(100vh-18px)] md:px-6">
                  <Navbar />
                  {children}
                  <div className="flex h-24 w-full shrink-0 items-center justify-center justify-self-end border-t border-border/40 text-center text-sm text-primary/60">
                    ©️ {new Date().getFullYear()} Crafted by{' '}
                    <div className={cn('ml-1 text-base', windsong.className)}>
                      Craig Hart
                    </div>
                  </div>
                </div>
              </div>
            </main>
          </StyledJsxProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
